name: repeatly
description: A daily reminder app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/splash.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
